import {
  ApprovalRequest,
  AuditLogEntry,
  CoreApplication,
  Customer,
  Interaction,
  TimelineEvent,
  User,
} from "./types";

const H = (hoursAgo: number) =>
  new Date(Date.now() - hoursAgo * 3600 * 1000).toISOString();
const HF = (hoursFromNow: number) =>
  new Date(Date.now() + hoursFromNow * 3600 * 1000).toISOString();

export const seedUsers: User[] = [
  { userId: "AG-001", name: "Mohamed Ali", role: "AGENT", presence: "AVAILABLE" },
  { userId: "AG-002", name: "Sara Al Mazrouei", role: "AGENT", presence: "AVAILABLE" },
  { userId: "MGR-001", name: "Khalifa Aldhaheri", role: "MANAGER", presence: "AVAILABLE" },
];

export const seedCustomers: Customer[] = [
  {
    customerId: "CUST-001",
    emiratesId: "784-1985-1234567-1",
    uid: "AB1234567",
    name: "Ahmed Al Falasi",
    phone: "+971-50-123-4567",
    email: "ahmed.alfalasi@example.com",
    language: "Arabic",
    segment: "Premium",
    flags: ["VIP"],
  },
  {
    customerId: "CUST-002",
    emiratesId: "784-1990-7654321-2",
    uid: "CD9876543",
    name: "Fatima Al Suwaidi",
    phone: "+971-55-765-4321",
    email: "fatima.suwaidi@example.com",
    language: "English",
    segment: "Standard",
    flags: [],
  },
  {
    customerId: "CUST-003",
    emiratesId: "784-1978-2223344-5",
    name: "Rashid Al Nuaimi",
    phone: "+971-52-999-8877",
    email: "rashid.nuaimi@example.com",
    language: "Arabic",
    segment: "Standard",
    flags: ["Sensitive Case"],
  },
];

export const seedInteractions: Interaction[] = [
  {
    interactionId: "INT-001",
    customerId: "CUST-001",
    mode: "PHYSICAL",
    type: "APPOINTMENT",
    assignedTo: "AG-001",
    serviceName: "Emirates ID Renewal",
    priority: "MEDIUM",
    slaSecondsRemaining: 620,
    status: "IN_SERVICE",
    appointment: {
      id: "APT-1001",
      datetime: H(0.5),
      bookedVia: "Mobile App",
      referenceNo: "REF-88213",
    },
    queue: {
      token: "A-014",
      counter: "Counter 3",
      checkedInAt: H(0.4),
      calledAt: H(0.3),
      startedAt: H(0.2),
      waitSeconds: 360,
      servedByUserId: "AG-001",
    },
    createdAt: H(0.5),
    updatedAt: H(0.2),
  },
  {
    interactionId: "INT-002",
    customerId: "CUST-002",
    mode: "PHYSICAL",
    type: "WALKIN",
    assignedTo: "AG-002",
    serviceName: "Address Update",
    priority: "LOW",
    slaSecondsRemaining: 1500,
    status: "ARRIVED",
    queue: {
      token: "W-007",
      checkedInAt: H(0.2),
      waitSeconds: 720,
    },
    createdAt: H(0.2),
    updatedAt: H(0.2),
  },
  {
    interactionId: "INT-003",
    customerId: "CUST-003",
    mode: "VIRTUAL",
    type: "APPOINTMENT",
    assignedTo: "AG-001",
    serviceName: "Visa Status Inquiry",
    priority: "HIGH",
    slaSecondsRemaining: 900,
    status: "BOOKED",
    appointment: {
      id: "APT-1002",
      datetime: HF(1),
      bookedVia: "Mobile App",
      referenceNo: "REF-88214",
      virtualJoinUrl: "https://meet.demo.local/session/apt-1002",
    },
    createdAt: H(3),
    updatedAt: H(3),
  },
  {
    interactionId: "INT-004",
    customerId: "CUST-001",
    mode: "PHYSICAL",
    type: "APPOINTMENT",
    assignedTo: "AG-002",
    serviceName: "Document Attestation",
    priority: "MEDIUM",
    slaSecondsRemaining: 0,
    status: "COMPLETED",
    appointment: {
      id: "APT-1003",
      datetime: H(30),
      bookedVia: "Mobile App",
      referenceNo: "REF-87990",
    },
    queue: {
      token: "A-002",
      counter: "Counter 1",
      checkedInAt: H(30),
      calledAt: H(29.9),
      startedAt: H(29.8),
      completedAt: H(29.5),
      waitSeconds: 360,
      servedByUserId: "AG-002",
    },
    createdAt: H(30),
    updatedAt: H(29.5),
  },
  {
    interactionId: "INT-005",
    customerId: "CUST-002",
    mode: "VIRTUAL",
    type: "APPOINTMENT",
    assignedTo: "AG-001",
    serviceName: "Eligibility Review",
    priority: "HIGH",
    slaSecondsRemaining: 300,
    status: "IN_SERVICE",
    appointment: {
      id: "APT-1004",
      datetime: H(0.1),
      bookedVia: "Mobile App",
      referenceNo: "REF-88220",
      virtualJoinUrl: "https://meet.demo.local/session/apt-1004",
    },
    createdAt: H(4),
    updatedAt: H(0.1),
  },
  {
    interactionId: "INT-006",
    customerId: "CUST-003",
    mode: "PHYSICAL",
    type: "WALKIN",
    assignedTo: "AG-002",
    serviceName: "Sponsor Transfer Inquiry",
    priority: "MEDIUM",
    slaSecondsRemaining: 480,
    status: "CALLED",
    queue: {
      token: "W-011",
      counter: "Counter 2",
      checkedInAt: H(0.6),
      calledAt: H(0.05),
      waitSeconds: 1980,
      servedByUserId: "AG-002",
    },
    createdAt: H(0.6),
    updatedAt: H(0.05),
  },
  {
    interactionId: "INT-007",
    customerId: "CUST-001",
    mode: "PHYSICAL",
    type: "WALKIN",
    assignedTo: "AG-001",
    serviceName: "Card Replacement",
    priority: "LOW",
    slaSecondsRemaining: 0,
    status: "NO_SHOW",
    queue: {
      token: "W-002",
      checkedInAt: H(50),
      calledAt: H(49.5),
    },
    createdAt: H(50),
    updatedAt: H(49),
  },
  {
    interactionId: "INT-008",
    customerId: "CUST-002",
    mode: "PHYSICAL",
    type: "APPOINTMENT",
    assignedTo: "AG-002",
    serviceName: "Profile Correction",
    priority: "LOW",
    slaSecondsRemaining: 0,
    status: "CANCELLED",
    appointment: {
      id: "APT-1000",
      datetime: H(72),
      bookedVia: "Mobile App",
      referenceNo: "REF-87500",
    },
    createdAt: H(80),
    updatedAt: H(72),
  },
];

function timelineFor(
  customerId: string,
  interactionId: string | undefined,
  items: Array<[TimelineEvent["type"], string, string, number, string, TimelineEvent["sensitivity"]?]>
): TimelineEvent[] {
  return items.map(([type, title, details, hoursAgo, source, sensitivity], idx) => ({
    id: `EVT-${customerId.slice(-3)}-${idx.toString().padStart(2, "0")}`,
    customerId,
    interactionId,
    type,
    title,
    details,
    createdAt: H(hoursAgo),
    source,
    sensitivity: sensitivity ?? "NORMAL",
  }));
}

export const seedTimeline: TimelineEvent[] = [
  ...timelineFor("CUST-001", "INT-001", [
    ["APPOINTMENT", "Appointment booked", "Emirates ID Renewal booked via mobile app for today.", 24, "M365"],
    ["VISIT", "Kiosk check-in", "Checked in at kiosk, queue token A-014 issued.", 0.4, "Kiosk"],
    ["CASE", "Renewal case opened", "Core application case ADG-CA-5501 opened for ID renewal.", 0.35, "CoreApp"],
    ["CALL", "Reminder call", "Automated reminder call placed 24h before appointment.", 25, "ServiceNow"],
    ["COMPLAINT", "Complaint resolved: long wait time", "Customer complained about a 45-minute wait last visit. Resolved with service recovery voucher.", 480, "ServiceNow"],
    ["EMAIL", "Renewal confirmation email", "Sent renewal confirmation and required document checklist.", 26, "M365"],
    ["CHAT", "Chatbot session", "Customer asked chatbot about renewal fees.", 100, "M365"],
    ["SOCIAL", "Twitter mention", "Customer tagged support handle asking about renewal timelines.", 200, "Sprinklr"],
    ["CASE", "Previous ID issued", "Original Emirates ID issued, valid 10 years.", 8760, "CoreApp"],
    ["VISIT", "Branch visit - document attestation", "Visited Al Barsha branch for attestation service.", 720, "ServiceNow"],
    [
      "CASE",
      "Financial hardship exception noted",
      "Customer requested fee waiver citing financial hardship; bank statement on file shows salary details.",
      500,
      "CoreApp",
      "SENSITIVE",
    ],
    [
      "COMPLAINT",
      "Data correction request (sensitive)",
      "Customer requested correction to medical fitness test result linked to a prior health condition.",
      300,
      "ServiceNow",
      "SENSITIVE",
    ],
  ]),
  ...timelineFor("CUST-002", "INT-002", [
    ["VISIT", "Walk-in registered", "Registered as walk-in at kiosk, queue token W-007 issued.", 0.2, "Kiosk"],
    ["CASE", "Address update case opened", "Core application case ADG-CA-5502 opened.", 0.18, "CoreApp"],
    ["APPOINTMENT", "Virtual appointment booked", "Eligibility Review virtual appointment booked via mobile app.", 4.2, "M365"],
    ["CALL", "Inbound call - document query", "Customer called asking which documents are required for address update.", 6, "ServiceNow"],
    ["EMAIL", "Document request sent", "Requested Utility Bill and Tenancy Contract.", 5, "M365"],
    ["CASE", "Missing documents flagged", "Utility Bill missing, Tenancy Contract marked invalid (expired).", 3, "CoreApp"],
    ["COMPLAINT", "Complaint resolved: incorrect SMS", "Customer received a duplicate SMS notification; corrected and apologized.", 240, "ServiceNow"],
    ["CHAT", "Web chat - eligibility question", "Asked about eligibility for fee exemption.", 50, "M365"],
    ["SOCIAL", "Instagram DM", "Asked about processing time via Instagram DM.", 150, "Sprinklr"],
    ["VISIT", "Previous branch visit", "Visited Deira branch for profile verification.", 900, "ServiceNow"],
    [
      "CASE",
      "Sensitive: prior fraud flag review",
      "Account was reviewed for a suspected fraud flag in a prior year; cleared after investigation.",
      1000,
      "CoreApp",
      "SENSITIVE",
    ],
  ]),
  ...timelineFor("CUST-003", "INT-003", [
    ["APPOINTMENT", "Virtual appointment booked", "Visa Status Inquiry virtual appointment booked via mobile app.", 3, "M365"],
    ["CASE", "Sponsor transfer case opened", "Core application case ADG-CA-5503 opened for sponsor transfer review.", 2.5, "CoreApp"],
    ["VISIT", "Walk-in registered", "Registered as walk-in at kiosk for sponsor transfer inquiry, token W-011.", 0.6, "Kiosk"],
    ["CALL", "Inbound call - visa expiry", "Customer called concerned about sponsor visa expiry.", 10, "ServiceNow"],
    ["COMPLAINT", "Complaint resolved: delayed status update", "Status portal was not reflecting latest update; resolved and portal refreshed.", 600, "ServiceNow"],
    ["EMAIL", "Eligibility notice", "Sent notice that sponsor visa has expired and is blocking transfer eligibility.", 2, "M365"],
    ["CHAT", "Chatbot - eligibility rules", "Asked chatbot about exception process for expired sponsor visa.", 40, "M365"],
    ["SOCIAL", "Facebook comment", "Left a public comment asking about processing delays.", 300, "Sprinklr"],
    ["VISIT", "Previous branch visit", "Visited Al Ain branch for initial sponsor registration.", 2000, "ServiceNow"],
    ["CASE", "Prior sponsor registration", "Original sponsor registration case closed successfully.", 4000, "CoreApp"],
    [
      "COMPLAINT",
      "Sensitive: disability accommodation request",
      "Customer requested priority handling due to a disclosed disability; accommodation notes on file.",
      700,
      "ServiceNow",
      "SENSITIVE",
    ],
    [
      "CASE",
      "Sensitive: legal dispute reference",
      "Case references an ongoing legal dispute regarding sponsorship; handled with legal team involvement.",
      1500,
      "CoreApp",
      "SENSITIVE",
    ],
  ]),
];

export const seedCoreApplications: CoreApplication[] = [
  {
    appId: "APP-001",
    customerId: "CUST-001",
    interactionId: "INT-001",
    serviceName: "Emirates ID Renewal",
    status: "IN_PROGRESS",
    eligibility: { isEligible: true, reasons: [] },
    requiredDocs: [
      { name: "Passport Copy", status: "RECEIVED" },
      { name: "Proof of Address", status: "MISSING" },
    ],
    pendingSteps: ["Biometrics capture", "Fee payment confirmation"],
  },
  {
    appId: "APP-002",
    customerId: "CUST-002",
    interactionId: "INT-002",
    serviceName: "Address Update",
    status: "PENDING_DOCS",
    eligibility: { isEligible: true, reasons: [] },
    requiredDocs: [
      { name: "Emirates ID Copy", status: "RECEIVED" },
      { name: "Utility Bill", status: "MISSING" },
      { name: "Tenancy Contract", status: "INVALID" },
    ],
    pendingSteps: ["Resubmit valid tenancy contract", "Verify new address"],
  },
  {
    appId: "APP-003",
    customerId: "CUST-003",
    interactionId: "INT-003",
    serviceName: "Sponsor Transfer",
    status: "BLOCKED",
    eligibility: {
      isEligible: false,
      reasons: ["Sponsor visa expired", "Outstanding fines on file"],
    },
    requiredDocs: [
      { name: "Passport Copy", status: "RECEIVED" },
      { name: "New Sponsor Letter", status: "RECEIVED" },
      { name: "Fine Clearance Certificate", status: "MISSING" },
    ],
    pendingSteps: ["Clear outstanding fines", "Renew sponsor visa", "Re-submit transfer request"],
  },
  {
    appId: "APP-004",
    customerId: "CUST-002",
    interactionId: "INT-005",
    serviceName: "Eligibility Review",
    status: "IN_PROGRESS",
    eligibility: { isEligible: true, reasons: [] },
    requiredDocs: [{ name: "Salary Certificate", status: "RECEIVED" }],
    pendingSteps: ["Final eligibility sign-off"],
  },
];

export const seedApprovals: ApprovalRequest[] = [
  {
    approvalId: "APR-001",
    interactionId: "INT-002",
    customerId: "CUST-002",
    requestedByUserId: "AG-002",
    type: "DOCUMENT_WAIVER",
    title: "Waive Utility Bill requirement",
    justification:
      "Customer's utility account is still transferring into her name; Emirates ID copy and pending tenancy contract are sufficient to proceed.",
    payload: { docName: "Utility Bill", reason: "Utility account transfer in progress", expiryDays: 30 },
    status: "PENDING",
    createdAt: H(1),
  },
  {
    approvalId: "APR-002",
    interactionId: "INT-006",
    customerId: "CUST-003",
    requestedByUserId: "AG-002",
    type: "PRIORITY_OVERRIDE",
    title: "Escalate walk-in to HIGH priority",
    justification: "Customer has a connecting flight in 2 hours and needs the sponsor transfer inquiry expedited.",
    payload: { from: "MEDIUM", to: "HIGH" },
    status: "PENDING",
    createdAt: H(0.5),
  },
  {
    approvalId: "APR-003",
    interactionId: "INT-004",
    customerId: "CUST-001",
    requestedByUserId: "AG-001",
    type: "TRANSFER_APPROVAL",
    title: "Transfer document attestation to Sara Al Mazrouei",
    justification: "Mohamed is at capacity; Sara has availability at Counter 1 and speaks the customer's preferred language.",
    payload: { toUserId: "AG-002" },
    status: "APPROVED",
    createdAt: H(31),
    decidedAt: H(30.8),
    decidedByUserId: "MGR-001",
    decisionNotes: "Approved - Sara has bandwidth and language match.",
  },
  {
    approvalId: "APR-004",
    interactionId: "INT-003",
    customerId: "CUST-003",
    requestedByUserId: "AG-001",
    type: "EXCEPTION_ELIGIBILITY",
    title: "Grant eligibility exception for expired sponsor visa",
    justification: "Customer is a long-standing Premium-adjacent client; requesting exception to proceed with transfer despite expired sponsor visa.",
    payload: { rule: "Sponsor visa must be active", exceptionRequested: true },
    status: "REJECTED",
    createdAt: H(2.8),
    decidedAt: H(2.5),
    decidedByUserId: "MGR-001",
    decisionNotes: "Insufficient rationale; sponsor visa must be renewed first per policy ADG-POL-14.",
  },
  {
    approvalId: "APR-005",
    interactionId: "INT-001",
    customerId: "CUST-001",
    requestedByUserId: "AG-001",
    type: "FAST_TRACK",
    title: "VIP fast-track for Emirates ID renewal",
    justification: "Customer holds VIP/Premium segment status and requested expedited biometrics slot.",
    payload: { skipSteps: ["Standard queue re-verification"] },
    status: "PENDING",
    createdAt: H(0.15),
  },
];

export const seedAudit: AuditLogEntry[] = [
  {
    auditId: "AUD-0001",
    actorUserId: "SYSTEM",
    actorRole: "AGENT",
    actionType: "KIOSK_CHECKIN",
    entityType: "INTERACTION",
    entityId: "INT-001",
    interactionId: "INT-001",
    customerId: "CUST-001",
    timestamp: H(0.4),
    summary: "Kiosk check-in matched existing appointment for Ahmed Al Falasi; interaction marked ARRIVED.",
    channel: "SYSTEM",
    severity: "INFO",
  },
  {
    auditId: "AUD-0002",
    actorUserId: "SYSTEM",
    actorRole: "AGENT",
    actionType: "QUEUE_TOKEN_ISSUED",
    entityType: "QUEUE",
    entityId: "A-014",
    interactionId: "INT-001",
    customerId: "CUST-001",
    timestamp: H(0.4),
    summary: "Queue token A-014 issued for INT-001.",
    channel: "SYSTEM",
    severity: "INFO",
  },
  {
    auditId: "AUD-0003",
    actorUserId: "AG-001",
    actorRole: "AGENT",
    actionType: "TOKEN_CALLED",
    entityType: "QUEUE",
    entityId: "A-014",
    interactionId: "INT-001",
    customerId: "CUST-001",
    timestamp: H(0.3),
    summary: "Token A-014 called to Counter 3 by Mohamed Ali.",
    before: { status: "ARRIVED" },
    after: { status: "CALLED", counter: "Counter 3" },
    channel: "SYSTEM",
    severity: "INFO",
  },
  {
    auditId: "AUD-0004",
    actorUserId: "AG-001",
    actorRole: "AGENT",
    actionType: "SERVICE_STARTED",
    entityType: "INTERACTION",
    entityId: "INT-001",
    interactionId: "INT-001",
    customerId: "CUST-001",
    timestamp: H(0.2),
    summary: "Service started for INT-001 by Mohamed Ali.",
    before: { status: "CALLED" },
    after: { status: "IN_SERVICE" },
    channel: "SYSTEM",
    severity: "INFO",
  },
  {
    auditId: "AUD-0005",
    actorUserId: "SYSTEM",
    actorRole: "AGENT",
    actionType: "WALKIN_REGISTERED",
    entityType: "INTERACTION",
    entityId: "INT-002",
    interactionId: "INT-002",
    customerId: "CUST-002",
    timestamp: H(0.2),
    summary: "Walk-in registered for Fatima Al Suwaidi; queue token W-007 issued.",
    channel: "SYSTEM",
    severity: "INFO",
  },
  {
    auditId: "AUD-0006",
    actorUserId: "AG-002",
    actorRole: "AGENT",
    actionType: "APPROVAL_REQUESTED",
    entityType: "APPROVAL",
    entityId: "APR-001",
    interactionId: "INT-002",
    customerId: "CUST-002",
    timestamp: H(1),
    summary: "Sara Al Mazrouei requested a Document Waiver for Utility Bill on INT-002.",
    channel: "API",
    severity: "INFO",
  },
  {
    auditId: "AUD-0007",
    actorUserId: "AG-002",
    actorRole: "AGENT",
    actionType: "APPROVAL_REQUESTED",
    entityType: "APPROVAL",
    entityId: "APR-002",
    interactionId: "INT-006",
    customerId: "CUST-003",
    timestamp: H(0.5),
    summary: "Sara Al Mazrouei requested a Priority Override (MEDIUM to HIGH) on INT-006.",
    channel: "API",
    severity: "INFO",
  },
  {
    auditId: "AUD-0008",
    actorUserId: "AG-001",
    actorRole: "AGENT",
    actionType: "APPROVAL_REQUESTED",
    entityType: "APPROVAL",
    entityId: "APR-003",
    interactionId: "INT-004",
    customerId: "CUST-001",
    timestamp: H(31),
    summary: "Mohamed Ali requested a Transfer Approval to Sara Al Mazrouei on INT-004.",
    channel: "API",
    severity: "INFO",
  },
  {
    auditId: "AUD-0009",
    actorUserId: "MGR-001",
    actorRole: "MANAGER",
    actionType: "APPROVAL_DECIDED",
    entityType: "APPROVAL",
    entityId: "APR-003",
    interactionId: "INT-004",
    customerId: "CUST-001",
    timestamp: H(30.8),
    summary: "Khalifa Aldhaheri approved Transfer Approval APR-003; INT-004 reassigned to AG-002.",
    before: { status: "PENDING", assignedTo: "AG-001" },
    after: { status: "APPROVED", assignedTo: "AG-002" },
    channel: "MANAGER_UI",
    severity: "INFO",
  },
  {
    auditId: "AUD-0010",
    actorUserId: "AG-001",
    actorRole: "AGENT",
    actionType: "APPROVAL_REQUESTED",
    entityType: "APPROVAL",
    entityId: "APR-004",
    interactionId: "INT-003",
    customerId: "CUST-003",
    timestamp: H(2.8),
    summary: "Mohamed Ali requested an Eligibility Exception on INT-003.",
    channel: "API",
    severity: "INFO",
  },
  {
    auditId: "AUD-0011",
    actorUserId: "MGR-001",
    actorRole: "MANAGER",
    actionType: "APPROVAL_DECIDED",
    entityType: "APPROVAL",
    entityId: "APR-004",
    interactionId: "INT-003",
    customerId: "CUST-003",
    timestamp: H(2.5),
    summary: "Khalifa Aldhaheri rejected Eligibility Exception APR-004 on INT-003.",
    before: { status: "PENDING" },
    after: { status: "REJECTED" },
    channel: "MANAGER_UI",
    severity: "RISK",
  },
  {
    auditId: "AUD-0012",
    actorUserId: "AG-001",
    actorRole: "AGENT",
    actionType: "APPROVAL_REQUESTED",
    entityType: "APPROVAL",
    entityId: "APR-005",
    interactionId: "INT-001",
    customerId: "CUST-001",
    timestamp: H(0.15),
    summary: "Mohamed Ali requested a Fast-Track/VIP handling exception on INT-001.",
    channel: "API",
    severity: "INFO",
  },
  {
    auditId: "AUD-0013",
    actorUserId: "MGR-001",
    actorRole: "MANAGER",
    actionType: "VIEW_AS_AGENT_TOGGLED",
    entityType: "CUSTOMER",
    entityId: "CUST-001",
    customerId: "CUST-001",
    timestamp: H(5),
    summary: "Khalifa Aldhaheri enabled 'View as Agent' impersonation mode.",
    channel: "MANAGER_UI",
    severity: "SECURITY",
  },
  {
    auditId: "AUD-0014",
    actorUserId: "MGR-001",
    actorRole: "MANAGER",
    actionType: "VIEW_FULL_SENSITIVE_DATA",
    entityType: "CUSTOMER",
    entityId: "CUST-003",
    customerId: "CUST-003",
    timestamp: H(4.5),
    summary: "Khalifa Aldhaheri viewed full unmasked Emirates ID and sensitive timeline details for Rashid Al Nuaimi.",
    channel: "MANAGER_UI",
    severity: "SECURITY",
  },
  {
    auditId: "AUD-0015",
    actorUserId: "SYSTEM",
    actorRole: "AGENT",
    actionType: "TOKEN_CALLED",
    entityType: "QUEUE",
    entityId: "W-011",
    interactionId: "INT-006",
    customerId: "CUST-003",
    timestamp: H(0.05),
    summary: "Token W-011 called to Counter 2 by Sara Al Mazrouei.",
    before: { status: "ARRIVED" },
    after: { status: "CALLED", counter: "Counter 2" },
    channel: "SYSTEM",
    severity: "INFO",
  },
  {
    auditId: "AUD-0016",
    actorUserId: "SYSTEM",
    actorRole: "AGENT",
    actionType: "INTERACTION_STATUS_CHANGED",
    entityType: "INTERACTION",
    entityId: "INT-007",
    interactionId: "INT-007",
    customerId: "CUST-001",
    timestamp: H(49),
    summary: "INT-007 marked NO_SHOW after token W-002 was called and customer did not appear.",
    before: { status: "CALLED" },
    after: { status: "NO_SHOW" },
    channel: "SYSTEM",
    severity: "INFO",
  },
  {
    auditId: "AUD-0017",
    actorUserId: "MGR-001",
    actorRole: "MANAGER",
    actionType: "INTERACTION_STATUS_CHANGED",
    entityType: "INTERACTION",
    entityId: "INT-008",
    interactionId: "INT-008",
    customerId: "CUST-002",
    timestamp: H(72),
    summary: "Khalifa Aldhaheri cancelled INT-008 at customer's request via mobile app follow-up call.",
    before: { status: "BOOKED" },
    after: { status: "CANCELLED" },
    channel: "MANAGER_UI",
    severity: "INFO",
  },
  {
    auditId: "AUD-0018",
    actorUserId: "SYSTEM",
    actorRole: "AGENT",
    actionType: "SERVICE_COMPLETED",
    entityType: "INTERACTION",
    entityId: "INT-004",
    interactionId: "INT-004",
    customerId: "CUST-001",
    timestamp: H(29.5),
    summary: "INT-004 completed by Sara Al Mazrouei at Counter 1.",
    before: { status: "IN_SERVICE" },
    after: { status: "COMPLETED" },
    channel: "SYSTEM",
    severity: "INFO",
  },
];
